### ISSUE TITLE
connect experiment interface with simulation output

### ISSUE THREAD

**Issue by antonlaukemper** [PGiagkoulas/a9_fake_news_simulator#32]
We are now able to feed the program with input from the command line and there is a method for returning the output, but there is no way from the command line to tell the program where to put the output

**Comment by PGiagkoulas** [comment]
For now ONLY the exporter function has been implemented. Integration with the rest of the code will take place after implementation of multiple runs in the simulation, so as to make cleaner updates of the repository.

**Comment by PGiagkoulas** [comment]
Exporting function has been integrated into the simulation runs and the branch has been merged
