### ISSUE TITLE
Evaluation metrics

### ISSUE THREAD

**Issue by PGiagkoulas** [PGiagkoulas/a9_fake_news_simulator#4]
Evaluation method of the network should be implemented. Examples: reporting possible clustering, opinion spreading rate, final distribution etc.

**Comment by antonlaukemper** [comment]
continuously keeping track of certain metrics while the simulation runs

**Comment by antonlaukemper** [comment]
who called whom

**Comment by PGiagkoulas** [comment]
What kind of evaluation metrics can we use, based on the literature?

**Comment by antonlaukemper** [comment]
it would be ofc cool to visualize the network and opinions over time

**Comment by PGiagkoulas** [comment]
definitely. I can look into that, since I don't have anything heavy this week, until Manvi does the research on the evaluation metrics we can use.
