### ISSUE TITLE
Implement protocols

### ISSUE THREAD

**Issue by PGiagkoulas** [PGiagkoulas/a9_fake_news_simulator#6]
Two kinds of protocols can be adopted:

- Communication protocols will govern the initiation of contact between agents (who contacts whom, how, etc.).

- Conversation protocols will govern the interaction between agents (how opinions propagate when agents interact with each other, use of aggression etc.).

**Comment by antonlaukemper** [comment]
I am adding a separate conversation protocol

**Comment by antonlaukemper** [comment]
which protocols do we want to have implemented until tomorrow?

**Comment by PGiagkoulas** [comment]
at least the random discussion one he had already.  We could also try a directed graph approach as well.

**Comment by antonlaukemper** [comment]
LNS, CMO,
goal oriented:  aggressive agent connects/talks more, passive agents less.
- one-to-all/all-to-one:  all connections of an agent are used
- traveling news:  choose only agents that recently changed their beliefs.
- sequence:  all agent get a turn per time step.

**Comment by antonlaukemper** [comment]
new conversation protocol: simple one way communication
